COURSES = [
    {
        "name": "HTML & CSS",
        "nr_videos": 120,
        "nr_teachers": 2,
        "views": 1500,
        "price": 20,
        "img_id": "course-1",
    },
    {
        "name": "Art of Photography",
        "nr_videos": 50,
        "nr_teachers": 3,
        "views": 2100,
        "price": 32,
        "img_id": "course-2",
    },
    {
        "name": "React for Dummies",
        "nr_videos": 33,
        "nr_teachers": 1,
        "views": 13901,
        "price": 19,
        "img_id": "course-3",
    },
    {
        "name": "UI/UX Basics",
        "nr_videos": 110,
        "nr_teachers": 5,
        "views": 2999,
        "price": 200,
        "img_id": "course-4",
    },
    {
        "name": "Intro to C/C++",
        "nr_videos": 70,
        "nr_teachers": 4,
        "views": 43133,
        "price": 34,
        "img_id": "course-1",
    },
    {
        "name": "Science of Psychology",
        "nr_videos": 24,
        "nr_teachers": 6,
        "views": 12,
        "price": 20,
        "img_id": "course-2",
    },
    {
        "name": "Algorithms in Java",
        "nr_videos": 35,
        "nr_teachers": 7,
        "views": 5334,
        "price": 30,
        "img_id": "course-3",
    },
    {
        "name": "Digital Marketing 101",
        "nr_videos": 45,
        "nr_teachers": 2,
        "views": 8800,
        "price": 25,
        "img_id": "course-4",
    },
    {
        "name": "Advanced Python Programming",
        "nr_videos": 60,
        "nr_teachers": 3,
        "views": 5400,
        "price": 50,
        "img_id": "course-1",
    },
    {
        "name": "Blockchain Basics",
        "nr_videos": 40,
        "nr_teachers": 4,
        "views": 3000,
        "price": 45,
        "img_id": "course-2",
    },
]
